apiVersion: v1
kind: Service
metadata:
  name: {{ include "gor.fullname" . }}
  labels: {{ - include "gor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ - include "gor.selectorLabels" . | nindent 4 }}
